#!/bin/sh /etc/rc.common
# Copyright (C) 2014-2015 Xs
START=90

stop() {
	ps | grep "/usr/bin/adbyby/adbyby" | grep -v 'grep' | awk '{print $1}' |xargs kill -9
        iptables -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8118
}

start() {
        /usr/bin/adbyby/adbyby >/dev/null 2>&1 &
        iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8118
}

restart() {
        stop
        sleep 1
        start
}

